### ISSUE TITLE
sim_gsc.py problem

### ISSUE THREAD

**Issue by yuan9778** [fakufaku/pyramic-demo#3]
another problem I found is when I run python ./sim_gsc.pysim ; I got the following error:

D:\BF\pyramic-demo-master\sim>python sim_gsc.py
Traceback (most recent call last):
  File "sim_gsc.py", line 123, in <module>
    room.simulate()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\pyroomacoustics\room.py", line 2173, in simulate
    self.compute_rir()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\pyroomacoustics\room.py", line 2045, in compute_rir
    vis = self.visibility[s][m, :].astype(np.int32)
TypeError: 'NoneType' object is not subscriptable

I used Python3 in win10.

Many thanks.

**Comment by fakufaku** [comment]
Hum, pyroomacoustics has changed quite a bit during that time... Now when calling `room.simulate()` a second time, the room simulator state needs to be reset.

I have just pushed a commit (e0b02c1) to fix the script. Please let me know if it works for you!

**Comment by yuan9778** [comment]
It works now. Thanks much!
